name: koin_test
description: A testing library for koin, makes easy mock of definitions and module testing.
version: 0.14.0
homepage: https://github.com/datdt-97/koin.dart
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  koin:
    git:
      url: https://github.com/datdt-97/koin.dart
      path: /packages/koin
  kt_dart: ^1.0.0
  test: ^1.16.5
  meta: ^1.8.0
