name: koin
description: A pragmatic lightweight dependency injection framework for Dart projects.
version: 0.16.0
homepage: https://github.com/datdt-97/koin.dart
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  kt_dart: ^1.0.0
  meta: ^1.8.0
dev_dependencies:
  effective_dart: ^1.3.2
  test: ^1.16.5
