name: koin_bloc
description: A package to make it easier to use Bloc library with Koin.dart.
version: 0.2.0-nullsafety.1
homepage: https://github.com/pbissonho/koin.dart
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  koin:
    git:
      url: https://github.com/datdt-97/koin.dart
      path: /packages/koin
  
dev_dependencies:
  koin_test:
    git:
      url: https://github.com/datdt-97/koin.dart
      path: /packages/koin_test
